# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SportsTime' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SportsTime
  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'SDWebImage'
  pod 'SwiftyOnboard'
  pod 'SplashScreen'

  target 'SportsTimeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SportsTimeUITests' do
    # Pods for testing
  end

end
